name: Packager

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -p 407999 -a ME6gOZ61
      
